// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcPddaX1MvyzcxIv796NwIoRP-ctN5sBE',
    appId: '1:398169857149:web:734e51fe9cc28dd0c32514',
    messagingSenderId: '398169857149',
    projectId: 'telegram-chat-tg',
    authDomain: 'telegram-chat-tg.firebaseapp.com',
    storageBucket: 'telegram-chat-tg.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1UuH7xq-JwWehklHsnuO3NhznZEJguqQ',
    appId: '1:398169857149:android:aceea69cbce329a4c32514',
    messagingSenderId: '398169857149',
    projectId: 'telegram-chat-tg',
    storageBucket: 'telegram-chat-tg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLpBOxgROjdfXF9iXxUqi7W1Sm5e22Xq0',
    appId: '1:398169857149:ios:279a3e5cd3d499c2c32514',
    messagingSenderId: '398169857149',
    projectId: 'telegram-chat-tg',
    storageBucket: 'telegram-chat-tg.appspot.com',
    iosBundleId: 'com.example.lesson70',
  );
}
